fix: 로그인 화면 디자인, 로그인 요청 시 에러 처리
LikelionUniv/LikelionUniv_Frontend_University pull request #10
Opened 2024-01-18 04:24 UTC by chan-byeong

- 로그인 화면에서 요소가 전체 너비 넘어가지 않도록 수정

- 로그인 요청 에러 시 isUser에 undefined가 담기도록 수정

2024-01-18 04:57 UTC, jinhokim98 requested changes
아직 첫 번째 이슈가 해결이 되지 않았습니다. 코멘트 확인해주세요

2024-01-18 04:57 UTC, jinhokim98 commented on src/components/login/LoginStyle.tsx
>  `;
<img width="209" alt="image" src="https://github.com/LikelionUniv/LikelionUniv_Frontend_University/assets/81083461/703f48de-e836-4732-986c-ce2fe8b9a146">

800px일 때는 해결이 된 것 같으나 여전히 비슷한 현상이 유지되는 상황입니다.

2024-01-18 06:59 UTC, chan-byeong commented
모바일 버전도 적용하여 수정하였습니다

2024-01-19 09:00 UTC, chan-byeong commented on src/components/login/LoginStyle.tsx
>  `;
모바일 버전도 적용하여 수정하였습니다

- 기존에 있던 MLogin 컴포넌트와 비슷한 방식으로 웹버전 로그인 컴포넌트(WLogin) 만들어두고
Login 컴포넌트에서 화면 너비에 따라 알맞은 컴포넌트(WLogin or MLogin)가 보이도록 수정하였습니다.

- 모바일 버전 컴포넌트에서 로그인 가능하도록 링크 연결해두었습니다.

- 로그인 완료 화면 모바일 버전도 적용해두었습니다.

2024-01-19 10:43 UTC, jinhokim98 commented on src/components/login/LoginStyle.tsx
>  `;
네 확인했습니다!

2024-01-19 10:44 UTC, jinhokim98 commented
병찬님 충돌 해결해서 올려주실 수 있을까요?

2024-01-19 11:15 UTC, merged